function T_total = KineticEnergy(t,L,Mb,Mr,r,t1Ds,t2Ds,t1s,t2s,xDs)
%KINETICENERGY
%    T_TOTAL = KINETICENERGY(T,L,MB,MR,R,T1DS,T2DS,T1S,T2S,XDS)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    21-Mar-2021 23:07:39

t2 = L.^2;
t3 = r.^2;
t4 = t1Ds.^2;
t5 = t2Ds.^2;
t6 = xDs.^2;
T_total = (Mb.*t6)./2.0+Mr.*t6+(Mr.*t2.*t4)./6.0+(Mr.*t2.*t5)./6.0+(Mr.*t3.*t4)./8.0+(Mr.*t3.*t5)./8.0+(L.*Mr.*t1Ds.*xDs.*cos(t1s))./2.0+(L.*Mr.*t2Ds.*xDs.*cos(t2s))./2.0;
