function massMatrix = massMatrix(L,Mb,Mr,r,t1s,t2s)
%MASSMATRIX
%    MASSMATRIX = MASSMATRIX(L,MB,MR,R,T1S,T2S)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    21-Mar-2021 23:07:43

t2 = cos(t1s);
t3 = cos(t2s);
t4 = L.^2;
t5 = r.^2;
t6 = t4.*4.0;
t7 = t5.*3.0;
t8 = (L.*Mr.*t2)./2.0;
t9 = (L.*Mr.*t3)./2.0;
t10 = t6+t7;
t11 = (Mr.*t10)./1.2e+1;
massMatrix = reshape([Mb+Mr.*2.0,t8,t9,t8,t11,0.0,t9,0.0,t11],[3,3]);
