function RVector = rVector(F1,F2,L,Mr,g,t1Ds,t2Ds,t1s,t2s)
%RVECTOR
%    RVECTOR = RVECTOR(F1,F2,L,MR,G,T1DS,T2DS,T1S,T2S)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    21-Mar-2021 23:07:43

t2 = sin(t1s);
t3 = sin(t2s);
RVector = [F1.*cos(t1s)+F2.*cos(t2s)+(L.*Mr.*t2.*t1Ds.^2)./2.0+(L.*Mr.*t3.*t2Ds.^2)./2.0;(L.*(F1-Mr.*g.*t2))./2.0;(L.*(F2-Mr.*g.*t3))./2.0];
